<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: barcamp
 * Date: Fri, 24 Jul 2015 17:24:52 +0200
 */

$conf['title'] = 'barcamp.ruhr';
$conf['lang'] = 'de-informal';
$conf['template'] = 'minimal';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';

// end auto-generated content
