<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: barcamp
 * Date: Thu, 18 Feb 2016 12:12:18 +0100
 */

$conf['title'] = 'barcamp.ruhr';
$conf['lang'] = 'de-informal';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['tpl']['minimal']['hide-entry-title'] = 1;

// end auto-generated content
