<?php
/*
 * Local plugin enable/disable settings
 *
 * Auto-generated by install script
 * Date: Fri, 24 Jul 2015 15:12:21 +0000
 */

$plugins['authad']    = 0;
$plugins['authldap']  = 0;
$plugins['authmysql'] = 0;
$plugins['authpgsql'] = 0;
